/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_Dispatcher */

#ifndef _Included_gnu_io_Dispatcher
#define _Included_gnu_io_Dispatcher
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: instance */
/*
 * Class:     gnu_io_Dispatcher
 * Method:    abort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_abort
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getBaudRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getBaudRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getDataBits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getDataBits
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getFlowControlMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getFlowControlMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getInputBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getInputBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getOutputBufferFree
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getOutputBufferFree
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getOutputBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getOutputBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getParity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getParity
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getPortType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getPortType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getStopBits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_getStopBits
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    getValidPortInfos
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_gnu_io_Dispatcher_getValidPortInfos
  (JNIEnv *, jobject);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isBI
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isBI
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isCD
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isCD
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isCTS
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isCTS
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isDataAvailable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isDataAvailable
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isDSR
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isDSR
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isDTR
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isDTR
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isFramingError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isFramingError
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isOutputBufferEmpty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isOutputBufferEmpty
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isOverrunError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isOverrunError
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPaperOut
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPaperOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isParityError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isParityError
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPortReadable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPortReadable
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPortWritable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPortWritable
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPrinterBusy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPrinterBusy
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPrinterError
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPrinterError
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPrinterSelected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPrinterSelected
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isPrinterTimedOut
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isPrinterTimedOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isRI
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isRI
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    isRTS
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gnu_io_Dispatcher_isRTS
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    readBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_readBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    restart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_restart
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    sendBreak
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_sendBreak
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setDTR
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setDTR
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setFlowControlMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setFlowControlMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setInputBufferSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setInputBufferSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_setMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setOutputBufferSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setOutputBufferSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setRTS
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setRTS
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    setSerialPortParams
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_setSerialPortParams
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    suspend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gnu_io_Dispatcher_suspend
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gnu_io_Dispatcher_version
  (JNIEnv *, jobject);

/*
 * Class:     gnu_io_Dispatcher
 * Method:    writeBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_gnu_io_Dispatcher_writeBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
