#!/bin/sh

set -e

RXTXJDK11PATH=/usr/lib/jdk1.1/lib
RXTXJDK12PATH=/usr/lib/jdk1.2/jre/lib/ext
RXTXLOCALJDK12PATH=/usr/local/jdk1.2/jre/lib/ext

case "$1" in
    configure*)
        ldconfig
	# JDK 1.1
	if [ -f $RXTXJDK11PATH/classes.zip ]; then
	    if [ -L $RXTXJDK11PATH/jcl.jar -o -e  $RXTXJDK11PATH/jcl.jar ]; then
		echo "$RXTXJDK11PATH/jcl.jar already exists."
	    else
		echo "creating symlinks for JDK 1.1"
		cd $RXTXJDK11PATH; ln -s ../../../share/java/jcl.jar .
	    fi
	fi
	# JDK 1.2 - Debian standard directory
	if [ -d $RXTXJDK12PATH ]; then
	    if [ -L $RXTXJDK12PATH/jcl.jar -o -e  $RXTXJDK12PATH/jcl.jar ]; then
		echo "$RXTXJDK12PATH/jcl.jar already exists."
	    else
		echo "creating symlinks for JDK 1.2"
		ARCH=`dpkg --print-architecture`
		echo "Arch: $ARCH"
		cd $RXTXJDK12PATH; ln -s ../../../../../share/java/jcl.jar .
		#jdk1.2/jre/lib/i386:
		cd $RXTXJDK12PATH/../../$ARCH/; ln -s /usr/lib/libSerial.so .
	    fi
	fi
	# JDK 1.2 - Debian standard directory
	if [ -d $RXTXLOCALJDK12PATH ]; then
	    if [ -L $RXTXLOCALJDK12PATH/jcl.jar -o -e  $RXTXJDK12PATH/jcl.jar ]; then
		echo "$RXTXLOCALJDK12PATH/jcl.jar already exists."
	    else
		echo "creating symlinks for JDK 1.2"
		ARCH=`dpkg --print-architecture`
		echo "Arch: $ARCH"
		cd $RXTXLOCALJDK12PATH; ln -s ../../../../../share/java/jcl.jar .
		#jdk1.2/jre/lib/i386:
		cd $RXTXLOCALJDK12PATH/../../$ARCH/; ln -s /usr/lib/libSerial.so .
	    fi
	fi
	echo "This serial driver has to be enabled through modifying javax.comm.properties"
	echo "provided by the javax.comm package from sun. You may copy a file with the "
	echo "right content named /etc/javax.comm.properties."
	echo
	echo "The javax.comm package from sun has to be installed, too."
        ;;
    *)
        ;;
esac

# providing symlink:
cd /usr/doc; ln -s ../share/doc/lib-rxtx-java .
