#!/bin/sh
curruser=$1
echo $curruser

if [ ! -d /var/lock ]
then
mkdir /var/lock
fi

chgrp uucp /var/lock
chmod 775 /var/lock
if [ ! `niutil -readprop / /groups/uucp users | grep $curruser > /dev/null` ]
then
 niutil -mergeprop / /groups/uucp users $curruser
fi
