#!/bin/bash
#
# This is a wrapper script for cross compiler executables.
# As the binary name is not equal on all linux systems, this script
# uses the first available compiler from the configuration file.
#
# (c) 2012, Alexander Christian <alex@root1.de>
# This file GPL v3 licensed!
#

#########################################

# get base-folder of wrapper
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR"/toolchain.conf
source "$DIR"/toolchain.func

#########################################

echo                                
echo "*********************************************"
echo "MinGW 32bit - Compiler Wrapper"
echo "---------------------------------------------"
echo "Detected OS: $OS_NAME $MACHINE"
if [ -z "$TOOLCHAIN_EXECUTABLE" ]; then 
	findExecutable "${WINDOWS_X86_EXEC[@]}"
else
	echo "-> Using preset executable name";	
fi
echo "Toolchain executable: $TOOLCHAIN_EXECUTABLE"
echo "*********************************************"
echo
if [ -z "$TOOLCHAIN_EXECUTABLE" ]; then
    echo "No toolchain executable name for os '$OS_NAME' found."
    echo "Please run 'export TOOLCHAIN_EXECUTABLE=/my/path/to/toolchain-executable' before build!"
    exit 1;
fi

# run the compiler
$TOOLCHAIN_EXECUTABLE "$@"

echo 
echo "*********************************************"
